## Tests for Ishigami function
Exact permutation. Analytical Shapley values obtained from Plischke, Rabitti, and Borgonovo (2020), p. 8. Inputs are independent.

In [12]:
import numpy as np
import pandas as pd
import chaospy as cp
from numpy.testing import assert_array_almost_equal as aaae

from econsa_shapley import get_shapley
from econsa_shapley import _r_condmvn
from econsa_sampling import cond_mvn

In [20]:
# Function inputs.
n_inputs = 8
perms = np.random.permutation(n_inputs)
j = 3
subset_j = perms[:j]
subsetj_conditional = perms[j:]
mean = np.zeros(n_inputs)
cov = np.identity(n_inputs)
cov

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [21]:
# What does x_cond from the test cases spit out?
def x_cond(n, subset_j, subsetj_conditional, xjc):
    if subsetj_conditional is None:
        cov_int = np.array(cov)
        cov_int = cov_int.take(subset_j, axis=1)
        cov_int = cov_int[subset_j]
        distribution = cp.MvNormal(mean[subset_j], cov_int)
        return distribution.sample(n)
    else:
        return _r_condmvn(
            n,
            mean=mean,
            cov=cov,
            dependent_ind=subset_j,
            given_ind=subsetj_conditional,
            x_given=xjc,
            )
    
n_outer = 10
xjc_sampled = np.array(x_cond(n_outer, subset_j=subset_j, subsetj_conditional=None, xjc=None)).T
xjc_sampled

array([[ 0.09288426, -0.70096866,  0.20345995],
       [ 0.3935221 , -0.49171081,  0.11105293],
       [ 1.05566788,  0.82159562,  2.26630739],
       [-0.3729004 , -1.71774639,  0.34176298],
       [ 1.27592753, -0.64264327,  0.25149838],
       [-0.53983651,  0.68467384,  0.14475023],
       [-0.81087072, -0.98345824, -0.76483583],
       [-0.72763581, -0.81165606, -0.55628117],
       [ 0.43206032,  0.63202395,  2.09558351],
       [ 0.27716319,  0.31380108,  1.00248804]])

In [22]:
length = 4
xjc = xjc_sampled[length, ]
xjc

array([ 1.27592753, -0.64264327,  0.25149838])

In [23]:
n_inner = 4
ich = np.array(x_cond(n_inner, subset_j, subsetj_conditional, xjc))
#sample_inputs = np.array(x_cond(n_inner, subset_j, subsetj_conditional, xjc.flat)).T.reshape(n_inner, -1, )
#sample_inputs

ValueError: lengths of given_value and given_ind must be the same

In [13]:
    cond_mean, cond_var = cond_mvn(
        mean,
        cov,
        dependent_ind=dependent_ind,
        given_ind=given_ind,
        given_value=x_given,
    )
    distribution = cp.MvNormal(cond_mean, cond_var)

    return distribution.sample(n)

NameError: name 'dependent_ind' is not defined

In [ ]:
def test_get_shapley_ishigami():
    def ishigami_function(x):
        return math.sin(x[:, 1]) * (1 + 0.1 * (x[:, 3] ** 4)) + 7 * (math.sin(x[:, 2]) ** 2)

    def x_all(n):
        distribution = cp.Uniform(lower, upper)
        return distribution.sample(n)

    def x_cond(n, subset_j, subsetj_conditional, xjc):
        
        # Wrong, since we need samples for the variables corresponding to the indices in sj(c)!
        if subsetj_conditional is None:
            
            distribution = cp.Uniform(lower, upper)
        return distribution.sample(n)
            return # ndarray with dim n_sim x no. of elements in subset_j, exactly for those input variables.
        else:
            return # ndarray  with dim n_sim x no. of elements in subsetj_conditional.

    np.random.seed(123)
    n_inputs = 3
    mean = np.zeros(3)
    # Lower and upper bound of the uniform distribution.
    lower = -math.pi
    upper = math.pi
    variance = (1/12) * ((upper - lower) ** 2)
    cov = np.array([[1.0, 0, 0], [0, 1.0, 1.8], [0, 1.8, 4.0]])
    method = "exact"
    n_perms = None
    n_output = 10 ** 4
    n_outer = 10 ** 3
    n_inner = 10 ** 2

    col = ["X" + str(i) for i in np.arange(n_inputs) + 1]
    names = ["Shapley effects", "std. errors", "CI_min", "CI_max"]

    expected = pd.DataFrame(
        data=[
            [0.101309, 0.418989, 0.479701],
            [0.00241549, 0.16297, 0.163071],
            [0.096575, 0.0995681, 0.160083],
            [0.106044, 0.73841, 0.79932],
        ],
        index=names,
        columns=col,
    ).T

    calculated = get_shapley(
        method,
        gaussian_model,
        x_all,
        x_cond,
        n_perms,
        n_inputs,
        n_output,
        n_outer,
        n_inner,
    )

    aaae(calculated, expected)

In [21]:
# Example.
n_inputs = 7
n_sim = 10
perms = np.random.permutation(n_inputs)
j = 4
subset_j = perms[:j]
subsetj_conditional = perms[j:]
lower = 0
upper = 1
out = np.zeros((n_sim, n_inputs))
for i in subset_j:
    out[:, i] = cp.Uniform(lower, upper).sample(n_sim).T
out

array([[0.38377533, 0.        , 0.27999478, 0.        , 0.        ,
        0.47232937, 0.55148138],
       [0.16606031, 0.        , 0.49768564, 0.        , 0.        ,
        0.43442878, 0.46587021],
       [0.85391958, 0.        , 0.50341559, 0.        , 0.        ,
        0.36058198, 0.2781392 ],
       [0.53300291, 0.        , 0.50630399, 0.        , 0.        ,
        0.52169385, 0.53213383],
       [0.91287332, 0.        , 0.24418302, 0.        , 0.        ,
        0.0477079 , 0.12106805],
       [0.70604899, 0.        , 0.68216086, 0.        , 0.        ,
        0.84896816, 0.66360917],
       [0.57615931, 0.        , 0.23240094, 0.        , 0.        ,
        0.59900273, 0.65371224],
       [0.99222253, 0.        , 0.48436874, 0.        , 0.        ,
        0.73214416, 0.43902138],
       [0.02985574, 0.        , 0.72488381, 0.        , 0.        ,
        0.63781945, 0.09538967],
       [0.00731334, 0.        , 0.94950301, 0.        , 0.        ,
        0.25366271, 0.1

In [19]:
def x_cond(n, subset_j, subsetj_conditional, xjc):
        distribution = cp.Uniform(lower, upper)
        return distribution.sample(n)

In [ ]:
def x_cond(n, subset_j, subsetj_conditional, xjc):
        
        # Wrong, since we need samples for the variables corresponding to the indices in sj(c)!
        if subsetj_conditional is None:
            
            distribution = cp.Uniform(lower, upper)
        return distribution.sample(n)
            return # ndarray with dim n_sim x no. of elements in subset_j, exactly for those input variables.
        else:
            return # ndarray  with dim n_sim x no. of elements in subsetj_conditional.

In [ ]:
# Call the function.
x_cond(
    n=n_sim,
    subset_j=subset_j,
    subsetj_conditional=subsetj_conditional,
    
      )