# Understand x_cond().

In [1]:
import numpy as np
import chaospy as cp

from econsa_shapley import get_shapley
from econsa_shapley import _r_condmvn
from econsa_sampling import cond_mvn

In [2]:
def x_cond(n, subset_j, subsetj_conditional, xjc):
    if subsetj_conditional is None:
        cov_int = np.array(cov)
        cov_int = cov_int.take(subset_j, axis=1)
        cov_int = cov_int[subset_j]
        distribution = cp.MvNormal(mean[subset_j], cov_int)
        return distribution.sample(n)
    else:
        return _r_condmvn(
            n,
            mean=mean,
            cov=cov,
            dependent_ind=subset_j,
            given_ind=subsetj_conditional,
            x_given=xjc,
        )

In [48]:
# Define all other arguments.
n_inputs = 7
n_outer = 10
n_inner = 4
np.random.seed(123)
perms = np.random.permutation(n_inputs)
j = 3
sj = perms[:j]
sjc = perms[j:]
cov = np.identity(n_inputs)
mean = np.zeros(n_inputs)

In [49]:
xjc_sampled = np.array(x_cond(n_outer, sjc, None, None)).T
length = 4  # Needs to be in range(n_outer).
xjc = xjc_sampled[length,]

In [50]:
sjc

array([0, 2, 5, 6])

In [51]:
xjc

array([ 0.20111148, -1.38043429, -0.72406513,  0.5055202 ])

In [52]:
xjc_sampled

array([[ 0.5803192 ,  0.50937464, -0.36453594, -1.01908106],
       [-0.02226337,  0.23759504, -0.20903631, -1.42494548],
       [ 0.77228698,  0.3366033 ,  0.39809876,  1.2258142 ],
       [-0.22516779, -0.15031721, -0.3218018 ,  0.67568196],
       [ 0.20111148, -1.38043429, -0.72406513,  0.5055202 ],
       [-1.08054058,  0.56020497,  2.25697836,  0.02949068],
       [-0.25071416, -0.18181619,  0.72572381, -0.08968679],
       [ 0.32475569, -0.53079478,  0.76211542,  0.17238023],
       [-0.45612265, -0.01984182, -1.91131658, -0.51708201],
       [-0.69107477,  0.64425943, -0.93883974, -0.00674592]])

In [53]:
xjc_sampled.shape

(10, 4)

In [54]:
sample_inputs = np.array(x_cond(n_inner, sj, sjc, xjc.flat)).T.reshape(
    n_inner,
    -1,)

In [55]:
sample_inputs

array([[ 0.47684265, -0.72953926,  0.8335348 ],
       [ 1.38320293, -0.15893343, -0.5748306 ],
       [-1.23224413,  0.67935333, -0.16767816],
       [-0.01130065, -0.04791466, -2.33555015]])

In [56]:
sample_inputs.shape

(4, 3)

In [57]:
np.ones((n_inner, 1)) * xjc

array([[ 0.20111148, -1.38043429, -0.72406513,  0.5055202 ],
       [ 0.20111148, -1.38043429, -0.72406513,  0.5055202 ],
       [ 0.20111148, -1.38043429, -0.72406513,  0.5055202 ],
       [ 0.20111148, -1.38043429, -0.72406513,  0.5055202 ]])